import { NextRequest } from 'next/server';
import mongoose from 'mongoose';
import { connectDB } from '@/lib/db';
import { verifyToken } from '@/lib/jwt';
import { errorResponse, serverErrorResponse, unauthorizedResponse } from '@/lib/api-response';
import { assertLecturerCourseAccess, buildLecturerReport, LecturerReportData, ReportItemType } from '@/lib/projects-and-tasks/lecturerReports';

function csvEscape(value: string | number | null | undefined): string {
  if (value === null || value === undefined) return '';
  const raw = String(value);
  if (/[",\n]/.test(raw)) {
    return `"${raw.replace(/"/g, '""')}"`;
  }
  return raw;
}

function buildCsv(report: LecturerReportData): string {
  const headerRows = [
    ['SmartLMS Lecturer Report'],
    ['Course', report.courseName],
    ['Generated At', new Date(report.generatedAt).toLocaleString('en-GB')],
    ['Item Type', report.itemType],
    [],
    ['Summary'],
    ['Total Students', report.kpis.totalStudents],
    ['Total Assigned', report.kpis.totalAssigned],
    ['Total Done', report.kpis.totalDone],
    ['Total In Progress', report.kpis.totalInProgress],
    ['Total Todo', report.kpis.totalTodo],
    ['Total Overdue', report.kpis.totalOverdue],
    ['Completion Rate (%)', report.kpis.completionRate],
    [],
    ['Student Name', 'Student ID', 'Assigned', 'Done', 'In Progress', 'Todo', 'Overdue', 'Completion Rate (%)', 'Last Activity'],
  ];

  const bodyRows = report.students.map((row) => [
    row.studentName,
    row.studentIdNumber,
    row.assigned,
    row.done,
    row.inProgress,
    row.todo,
    row.overdue,
    row.completionRate,
    row.lastActivity ? new Date(row.lastActivity).toLocaleString('en-GB') : '-',
  ]);

  return [...headerRows, ...bodyRows]
    .map((row) => row.map((cell) => csvEscape(cell)).join(','))
    .join('\n');
}

function sanitizePdfText(input: string): string {
  return input
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
    .replace(/[^\x20-\x7E]/g, '?');
}

function buildPdf(report: LecturerReportData): Buffer {
  const rows = report.students.slice(0, 18);
  const commands: string[] = [];

  commands.push('0.141 0.176 0.4 rg');
  commands.push('0 770 595 72 re f');

  commands.push('BT /F1 24 Tf 1 1 1 rg 36 812 Td (SmartLMS) Tj ET');
  commands.push('BT /F1 11 Tf 0.95 0.95 0.95 rg 36 794 Td (Projects and Tasks - Lecturer Report) Tj ET');
  commands.push(`BT /F1 11 Tf 0.95 0.95 0.95 rg 36 778 Td (${sanitizePdfText(report.courseName)}) Tj ET`);

  commands.push('BT /F1 10 Tf 0.2 0.2 0.2 rg 36 748 Td (Generated:) Tj ET');
  commands.push(`BT /F1 10 Tf 0.2 0.2 0.2 rg 92 748 Td (${sanitizePdfText(new Date(report.generatedAt).toLocaleString('en-GB'))}) Tj ET`);

  commands.push('0.965 0.976 1 rg');
  commands.push('36 706 523 30 re f');
  commands.push('BT /F1 10 Tf 0.1 0.16 0.31 rg 44 718 Td (Summary Metrics) Tj ET');
  commands.push(`BT /F1 10 Tf 0.15 0.15 0.15 rg 160 718 Td (Students: ${report.kpis.totalStudents}   Assigned: ${report.kpis.totalAssigned}   Done: ${report.kpis.totalDone}   Overdue: ${report.kpis.totalOverdue}   Completion: ${report.kpis.completionRate}%) Tj ET`);

  commands.push('0.141 0.176 0.4 rg');
  commands.push('36 680 523 18 re f');
  commands.push('BT /F1 9 Tf 1 1 1 rg 42 686 Td (Student) Tj ET');
  commands.push('BT /F1 9 Tf 1 1 1 rg 212 686 Td (ID) Tj ET');
  commands.push('BT /F1 9 Tf 1 1 1 rg 300 686 Td (Progress) Tj ET');
  commands.push('BT /F1 9 Tf 1 1 1 rg 452 686 Td (Rate) Tj ET');
  commands.push('BT /F1 9 Tf 1 1 1 rg 506 686 Td (Overdue) Tj ET');

  let y = 666;
  rows.forEach((row, idx) => {
    if (idx % 2 === 0) {
      commands.push('0.97 0.97 0.97 rg');
      commands.push(`36 ${y - 2} 523 16 re f`);
    }

    const progressText = `${row.done}/${row.assigned} done, ${row.inProgress} in progress, ${row.todo} todo`;
    commands.push(`BT /F1 8 Tf 0.15 0.15 0.15 rg 42 ${y + 3} Td (${sanitizePdfText(row.studentName.slice(0, 30))}) Tj ET`);
    commands.push(`BT /F1 8 Tf 0.15 0.15 0.15 rg 212 ${y + 3} Td (${sanitizePdfText(row.studentIdNumber)}) Tj ET`);
    commands.push(`BT /F1 8 Tf 0.15 0.15 0.15 rg 300 ${y + 3} Td (${sanitizePdfText(progressText.slice(0, 42))}) Tj ET`);
    commands.push(`BT /F1 8 Tf 0.15 0.15 0.15 rg 456 ${y + 3} Td (${row.completionRate}%) Tj ET`);
    commands.push(`BT /F1 8 Tf 0.15 0.15 0.15 rg 515 ${y + 3} Td (${row.overdue}) Tj ET`);

    y -= 18;
  });

  commands.push('BT /F1 8 Tf 0.45 0.45 0.45 rg 36 34 Td (Generated by SmartLMS Reports) Tj ET');

  const content = commands.join('\n');

  const objects: string[] = [];
  objects.push('1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj');
  objects.push('2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj');
  objects.push('3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj');
  objects.push('4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj');
  objects.push(`5 0 obj << /Length ${Buffer.byteLength(content, 'utf8')} >> stream\n${content}\nendstream endobj`);

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [0];

  objects.forEach((obj) => {
    offsets.push(Buffer.byteLength(pdf, 'utf8'));
    pdf += `${obj}\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, 'utf8');
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  for (let i = 1; i <= objects.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, 'utf8');
}

export async function GET(request: NextRequest) {
  try {
    await connectDB();

    const authHeader = request.headers.get('authorization');
    const token = authHeader?.replace('Bearer ', '');
    if (!token) return unauthorizedResponse('No token provided');

    const payload = verifyToken(token);
    if (!payload || payload.userRole !== 'lecture') {
      return unauthorizedResponse('Unauthorized access - Only lecturers can access this endpoint');
    }

    const { searchParams } = new URL(request.url);
    const courseId = searchParams.get('courseId') || '';
    const itemType = (searchParams.get('itemType') || 'all') as ReportItemType;
    const studentId = searchParams.get('studentId') || undefined;
    const format = (searchParams.get('format') || 'csv').toLowerCase();

    if (!courseId || !mongoose.Types.ObjectId.isValid(courseId)) {
      return errorResponse('Valid course ID is required', { courseId: ['Course ID is required'] }, 400);
    }
    if (!['all', 'project', 'task'].includes(itemType)) {
      return errorResponse('Invalid itemType', { itemType: ['Valid values: all, project, task'] }, 400);
    }
    if (!['csv', 'pdf'].includes(format)) {
      return errorResponse('Invalid export format', { format: ['Use csv or pdf'] }, 400);
    }

    const hasAccess = await assertLecturerCourseAccess(courseId, payload.userId);
    if (!hasAccess) {
      return unauthorizedResponse('You do not have access to this module');
    }

    let report;
    try {
      report = await buildLecturerReport({ courseId, itemType, studentId });
    } catch (error) {
      if (error instanceof Error && error.message === 'INVALID_STUDENT') {
        return errorResponse('Invalid student for selected module', { studentId: ['Student is not in this module'] }, 400);
      }
      throw error;
    }

    if (!report) {
      return errorResponse('Module not found', { course: ['Module not found'] }, 404);
    }

    const safeCourse = report.courseName.replace(/[^a-zA-Z0-9_-]/g, '_');
    const dateStamp = new Date().toISOString().slice(0, 10);

    if (format === 'csv') {
      const csv = buildCsv(report);
      return new Response(csv, {
        status: 200,
        headers: {
          'Content-Type': 'text/csv; charset=utf-8',
          'Content-Disposition': `attachment; filename="smartlms_report_${safeCourse}_${dateStamp}.csv"`,
        },
      });
    }

    const pdfBuffer = buildPdf(report);
    return new Response(new Uint8Array(pdfBuffer), {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="smartlms_report_${safeCourse}_${dateStamp}.pdf"`,
      },
    });
  } catch (error: unknown) {
    console.error('Export lecturer report error:', error);
    return serverErrorResponse('An error occurred while exporting report');
  }
}
