package com.smartlms.feedback_service.dto.response;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

/**
 * Response DTO for POST /api/feedback/ai-detect.
 *
 * aiScore is the raw probability (0.0–1.0) that the text was generated by an AI.
 * A score of -1.0 means the detection service was unavailable; callers should
 * treat this as "unknown" and apply no penalty.
 *
 * label values: VERY_LIKELY_AI | LIKELY_AI | POSSIBLY_AI | HUMAN_WRITTEN | UNAVAILABLE
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AiDetectionResponse {

    /** Probability 0.0–1.0 that the text is AI-generated. -1.0 = service unavailable. */
    private double aiScore;

    /** True when aiScore >= 0.75. */
    @JsonProperty("isAiGenerated")
    private boolean isAiGenerated;

    /** Human-readable label for the detection result. */
    private String label;
}
